name: publish-service

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      targetImageRepositoryName: 
        type: string  
        default: "core-docker-local"
      directoryBuildPropsPath:
        required: true
        type: string
      dockerRegistry:
        type: string
        default: "europe-west4-docker.pkg.dev"
      dockerFilePath:  
        type: string
        default: "./Dockerfile"
      nugetRegistry: 
        type: string
        default: "https://nuget.pkg.github.com/the-farmer-trading/index.json"
        
    secrets:
      dockerUsername: 
        required: true
      dockerPassword:
        required: true        
      nugetUsername: 
        required: true
      nugetPassword:
        required: true        
        
jobs:

  get-semver:
    runs-on: ubuntu-latest
    outputs: 
      semanticVersion: ${{ steps.get-semantic-version.outputs.group1 }}
      majorVersion: ${{ steps.get-semantic-version-components.outputs.majorVersion }}
      minorVersion: ${{ steps.get-semantic-version-components.outputs.minorVersion }}
      patchVersion: ${{ steps.get-semantic-version-components.outputs.patchVersion }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        
    - name: SEMVER - Load
      id: read-properties
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ inputs.directoryBuildPropsPath }}
        
    - name: SEMVER - Determine
      id: get-semantic-version
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ steps.read-properties.outputs.content }}
        regex: '<Version>(.*?)</Version>'    

    - name: SEMVER - Components
      id: get-semantic-version-components
      shell: pwsh
      run: |
        $semanticVersion = "${{ steps.get-semantic-version.outputs.group1 }}"
        $majorVersion = $semanticVersion.Split('.')[0]
        $minorVersion = $semanticVersion.Split('.')[1]
        $patchVersion = $semanticVersion.Split('.')[2]
        "majorVersion=$majorVersion" >> $env:GITHUB_OUTPUT
        "minorVersion=$minorVersion" >> $env:GITHUB_OUTPUT
        "patchVersion=$patchVersion" >> $env:GITHUB_OUTPUT
  
  publish:
    runs-on: ubuntu-latest
    needs: get-semver
    steps:
    - name: Check out the repo
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675

    - name: DOCKER - Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerUsername }}
        password: ${{ secrets.dockerPassword }}
        registry: ${{ inputs.dockerRegistry }}
    
    - name: DOCKER - Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: DOCKER - Setup BuildX
      uses: docker/setup-buildx-action@v1
          
    - name: DOCKER - Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerFilePath }}
        push: true 
        build-args: |
          nugetUsername=${{ secrets.nugetUsername }}
          nugetPassword=${{ secrets.nugetPassword }}
        tags: |
          europe-west4-docker.pkg.dev/silvester-306016/silvester-docker/${{ inputs.imageName }}:${{ needs.get-semver.outputs.majorVersion }}
          europe-west4-docker.pkg.dev/silvester-306016/silvester-docker/${{ inputs.imageName }}:${{ needs.get-semver.outputs.majorVersion }}.${{ needs.get-semver.outputs.minorVersion }}
          europe-west4-docker.pkg.dev/silvester-306016/silvester-docker/${{ inputs.imageName }}:${{ needs.get-semver.outputs.majorVersion }}.${{ needs.get-semver.outputs.minorVersion }}.${{ needs.get-semver.outputs.patchVersion }}
          europe-west4-docker.pkg.dev/silvester-306016/silvester-docker/${{ inputs.imageName }}:latest

